name: Python Code Quality
on:
  push:
    branches:
      - "**"
    tags:
      - "*"
    
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v6
      - run: uv lock --locked

  linting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: astral-sh/setup-uv@v6
      - run: uvx ruff check .
  formatting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: astral-sh/setup-uv@v6
      - run: uvx ruff format --check .
  type_consistency:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: astral-sh/setup-uv@v6
      - run: uv run ty check

  build:
    runs-on: [ubuntu-latest]
    needs: [linting, formatting, type_consistency]
    steps:
      - uses: astral-sh/setup-uv@v6
      - run: uv build